# Generated by Django 5.2.1 on 2025-05-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_deviceuser_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="ping_frequency",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name="deviceuser",
            unique_together={("device", "user")},
        ),
        migrations.AddIndex(
            model_name="pings",
            index=models.Index(
                fields=["device", "-timestamp"], name="api_pings_device__623a99_idx"
            ),
        ),
    ]
